name: Release

on:
    push:
        tags:
            - "v[0-9]+.*"

permissions:
    contents: write

jobs:
    create_release:
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
            - id: create_release
              name: Create Release
              uses: softprops/action-gh-release@v1
              if: startsWith(github.ref, 'refs/tags/')
    release_assets:
        needs: create_release
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                include:
                    - build: linux-x64
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-gnu
                      artifact_name: "compilet-linux-amd64"
                    - build: linux-arm64
                      os: ubuntu-latest
                      target: aarch64-unknown-linux-gnu
                      artifact_name: "compilet-linux-arm64"
                    - build: macos-x64
                      os: macos-latest
                      target: x86_64-apple-darwin
                      artifact_name: "compilet-darwin-amd64"
                    - build: macos-arm64
                      os: macos-latest
                      target: aarch64-apple-darwin
                      artifact_name: "compilet-darwin-arm64"
                    - build: windows-x64
                      os: windows-latest
                      target: x86_64-pc-windows-msvc
                      artifact_name: "compilet-windows-amd64"
                    - build: linux-musl-x64
                      os: ubuntu-latest
                      target: x86_64-unknown-linux-musl
                      artifact_name: "compilet-linux-musl-amd64"
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v3

            - uses: actions-rs/toolchain@v1
              with:
                  toolchain: stable
                  profile: minimal
                  target: ${{ matrix.target }}

            - name: Install musl-tools
              run: sudo apt update && sudo apt install -y musl-tools
              if: matrix.build == 'linux-musl-x64'

            - name: Install gcc-aarch64-linux-gnu
              run: |
                  sudo apt update
                  sudo apt install -y gcc-aarch64-linux-gnu
                  echo "[target.aarch64-unknown-linux-gnu]\nlinker = \"aarch64-linux-gnu-gcc\"" >> ~/.cargo/config.toml
              if: matrix.build == 'linux-arm64'

            - name: Build
              run: cargo build --release --target ${{ matrix.target }}

            - name: Upload to Release
              uses: svenstaro/upload-release-action@v2
              if: matrix.os != 'windows-latest'
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/${{ matrix.target }}/release/compilet
                  asset_name: ${{ matrix.artifact_name }}
                  tag: ${{ github.ref }}

            - name: Upload to Release (Windows)
              uses: svenstaro/upload-release-action@v2
              if: matrix.os == 'windows-latest'
              with:
                  repo_token: ${{ secrets.GITHUB_TOKEN }}
                  file: target/${{ matrix.target }}/release/compilet.exe
                  asset_name: ${{ matrix.artifact_name }}.exe
                  tag: ${{ github.ref }}
